/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Freepoly.org (https://sketchfab.com/blackrray)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ibm-pcjr-4863-computer-freepolyorg-1c3c3cd0643d44d49a1771048da74c62
Title: IBM PCjr 4863 Computer-Freepoly.org
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials, errors } = useGLTF('/scene.gltf')
  console.log(errors); // Log loading errors
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.009}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.default_1001} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.default_1005} />
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.default_1002} />
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.default_1004} />
            <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.default_1003} />
            <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.default_1006} />
            <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.default_1007} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
