/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 comp.gltf 
Author: Mikkel Garde Blaase (https://sketchfab.com/plorigon)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/killer-beats-casette-mixstation-1cc1eda430c74e3ea8f39284b2fb01d8
Title: "Killer Beats" Casette Mixstation
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/comp.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-6.496, -0.033, 1.768]} rotation={[Math.PI, 1.282, Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low002_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low002_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[-6.539, 0.758, 1.633]} rotation={[Math.PI, 1.282, Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low003_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low003_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.423, -0.033, -8.574]} rotation={[0, -0.652, -Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low004_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low004_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.376, 0.829, -8.55]} rotation={[0, -0.169, -Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low009_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low009_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.834, 0.1, 1.818]} rotation={[0, 1.504, -Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low010_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low010_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[5.834, 0.932, 1.818]} rotation={[-Math.PI, -0.813, -Math.PI / 2]} scale={[1.054, 0.955, 0.996]}>
        <mesh geometry={nodes.casette_base_low011_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low011_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <group position={[13.58, 0.013, 8.036]} rotation={[0.037, 0.62, 1.549]}>
        <mesh geometry={nodes.casette_base_low012_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} />
        <mesh geometry={nodes.casette_base_low012_M_Details_0.geometry} material={materials.M_Details} />
      </group>
      <mesh geometry={nodes.kb_base_low001_M_Keyboard_0.geometry} material={materials.M_Keyboard} position={[0.04, 0.756, 6.778]} rotation={[-Math.PI, 0.126, 0]} />
      <mesh geometry={nodes.SM_Keyboard_Lid_M_Keyboard_Translucent_0.geometry} material={materials.M_Keyboard_Translucent} position={[8.402, 2.044, 8.468]} rotation={[3.123, 0.126, 0.002]} />
      <mesh geometry={nodes.SM_Monitor_M_Monitor_0.geometry} material={materials.M_Monitor} position={[-0.801, 6.601, -3.287]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.strip_low_M_Details_0.geometry} material={materials.M_Details} position={[4.159, 0.963, -12.62]} rotation={[-2.809, 0.338, 1.019]} />
      <mesh geometry={nodes.SM_Cables_M_Details_0.geometry} material={materials.M_Details} position={[12.352, 6.021, -3.062]} rotation={[Math.PI / 2, 0, 0.244]} />
      <mesh geometry={nodes.ductTape_low_M_Details_0.geometry} material={materials.M_Details} position={[0.171, 0.208, -15.174]} rotation={[3.094, -0.031, -0.009]} />
      <mesh geometry={nodes.tape_base_low001_M_Details_0.geometry} material={materials.M_Details} position={[-4.459, 12.139, -3.273]} rotation={[0.027, -0.935, 0.027]} />
      <mesh geometry={nodes.SM_Speakers_M_Speakers_0.geometry} material={materials.M_Speakers} position={[11.809, 2.21, -0.194]} rotation={[Math.PI / 2, 0, 0.36]} scale={1.271} />
      <mesh geometry={nodes.ductTape_low001_M_Details_0.geometry} material={materials.M_Details} position={[11.733, 4.474, -3.962]} rotation={[-2.749, -0.011, 3.088]} scale={[-0.61, 0.61, 0.61]} />
      <mesh geometry={nodes.ductTape_low002_M_Details_0.geometry} material={materials.M_Details} position={[12.605, 1.255, -4.737]} rotation={[-2.144, -0.135, 3.071]} scale={[-0.61, 0.61, 0.61]} />
      <mesh geometry={nodes.strip_low001_M_Details_0.geometry} material={materials.M_Details} position={[17.863, -0.255, -3.352]} rotation={[2.994, -0.539, 0.189]} />
      <mesh geometry={nodes.strip_low002_M_Details_0.geometry} material={materials.M_Details} position={[16.831, -0.255, -0.237]} rotation={[0.433, -1.266, -2.461]} />
      <mesh geometry={nodes.tape_base_low003_M_Details_0.geometry} material={materials.M_Details} position={[-10.928, 0.003, 5.67]} rotation={[-0.059, -0.464, 1.554]} />
      <mesh geometry={nodes.tape_base_low004_M_Details_0.geometry} material={materials.M_Details} position={[8.176, 1.434, 10.294]} rotation={[-Math.PI, -1.434, -1.846]} />
      <mesh geometry={nodes.tape_base_low005_M_Details_0.geometry} material={materials.M_Details} position={[-10.205, 0.174, 4.237]} rotation={[3.017, -0.052, 1.602]} />
      <mesh geometry={nodes.casette_base_low005_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[-0.42, 12.292, -3.225]} rotation={[-3.139, 0.12, -1.574]} />
      <mesh geometry={nodes.casette_lid_low002_M_Details_0.geometry} material={materials.M_Details} position={[-0.267, 11.93, -4.482]} rotation={[-3.139, 0.12, -1.574]} />
      <mesh geometry={nodes.casette_base_low006_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[14.499, 0.881, 1.785]} rotation={[1.485, 0.169, 0.474]} />
      <mesh geometry={nodes.casette_lid_low003_M_Details_0.geometry} material={materials.M_Details} position={[14.392, -0.43, 1.731]} rotation={[1.485, 0.169, 0.474]} />
      <mesh geometry={nodes.casette_base_low007_M_Details_Translucent_0.geometry} material={materials.M_Details_Translucent} position={[-1.049, 13.008, -3.657]} rotation={[-3.139, -0.2, -1.573]} />
      <mesh geometry={nodes.casette_lid_low004_M_Details_0.geometry} material={materials.M_Details} position={[-1.299, 12.646, -4.898]} rotation={[-3.139, -0.2, -1.573]} />
      <mesh geometry={nodes.tape_base_low006_M_Details_0.geometry} material={materials.M_Details} position={[-9.285, 0.877, -1.199]} rotation={[1.571, -0.217, -0.06]} />
      <mesh geometry={nodes.tape_base_low007_M_Details_0.geometry} material={materials.M_Details} position={[11.71, 9.947, -0.395]} rotation={[-0.023, -0.824, 3.125]} />
      <mesh geometry={nodes.tape_base_low008_M_Details_0.geometry} material={materials.M_Details} position={[-7.233, 0.105, -8.262]} rotation={[-3.128, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.tape_base_low009_M_Details_0.geometry} material={materials.M_Details} position={[-7.232, 0.569, -8.32]} rotation={[-0.023, -0.079, 1.569]} />
      <mesh geometry={nodes.tape_base_low010_M_Details_0.geometry} material={materials.M_Details} position={[-7.858, -0.387, -7.884]} rotation={[1.558, -0.058, -1.414]} />
      <mesh geometry={nodes.tape_base_low011_M_Details_0.geometry} material={materials.M_Details} position={[-7.232, 0.96, -8.33]} rotation={[3.121, -0.262, -1.563]} />
      <mesh geometry={nodes.tape_base_low012_M_Details_0.geometry} material={materials.M_Details} position={[14.499, 0.881, 1.785]} rotation={[1.485, 0.169, 0.474]} />
      <mesh geometry={nodes.tape_base_low013_M_Details_0.geometry} material={materials.M_Details} position={[-1.049, 13.008, -3.657]} rotation={[-3.139, -0.2, -1.573]} />
      <mesh geometry={nodes.tape_base_low014_M_Details_0.geometry} material={materials.M_Details} position={[-0.42, 12.292, -3.225]} rotation={[-3.139, 0.12, 1.568]} />
      <mesh geometry={nodes.Plane_M_Floor_0.geometry} material={materials.M_Floor} position={[0.181, -0.518, 0.543]} rotation={[0, -0.47, 0]} scale={28.144} />
    </group>
  )
}

useGLTF.preload('/comp.gltf')
